### ISSUE TITLE
版本v2.1.7报错,之前v2.0.17正常

### ISSUE THREAD

**Issue by wenyifancc** [netptop/siteproxy#71]
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11731:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: InvalidArgumentError: invalid connection header
      at processHeader (node:internal/deps/undici/undici:6674:17)
      at new Request (node:internal/deps/undici/undici:6502:13)
      at [http1 build request] (node:internal/deps/undici/undici:6595:16)
      at [dispatch] (node:internal/deps/undici/undici:7697:139)
      at Intercept (node:internal/deps/undici/undici:7377:20)
      at [Intercepted Dispatch] (node:internal/deps/undici/undici:6007:16)
      at Client.dispatch (node:internal/deps/undici/undici:6023:44)
      at [dispatch] (node:internal/deps/undici/undici:6254:32)
      at [Intercepted Dispatch] (node:internal/deps/undici/undici:6000:33)
      at Pool.dispatch (node:internal/deps/undici/undici:6023:44) {
    code: 'UND_ERR_INVALID_ARG'
  }
}
```

**Comment by netptop** [comment]
这个问题是在访问哪个网站出现的？ 请提供具体复现方法，包括浏览器类型，电脑或者手机，具体URL等。  另外， 也请尝试下node v18,看看是否有同样的问题。

**Comment by wenyifancc** [comment]
操作方法:
修改config.json后使用docker启动
```
services:
  site-proxy:
    image: node:18
    container_name: site-proxy
    restart: unless-stopped
    ports:
      - 127.0.0.1:65006:5006
    volumes:
      - ./siteproxy/:/home/node/siteproxy/
    working_dir: /home/node/siteproxy/
    entrypoint: ["node","/home/node/siteproxy/bundle.js"]
```

同样方法在v2.0.17正常,之后的版本异常
浏览器:chrome 121.0.6167.189
OS:windows 11

url:
https://proxy.mydomain.name/test/

备注:proxy.mydomain.name为示例
